// <auto-generated />
using DiemRenLuyenMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiemRenLuyenMVC.Migrations
{
    [DbContext(typeof(DiemRenLuyenMVCContext))]
    partial class DiemRenLuyenMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiemRenLuyenMVC.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "22103100228",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100229",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100230",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100231",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100232",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103110301",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103110302",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103110303",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103199901",
                            MatKhau = "admin",
                            VaiTro = "CTSV"
                        },
                        new
                        {
                            TenDangNhap = "22103199902",
                            MatKhau = "admin",
                            VaiTro = "CTSV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
