// <auto-generated />
using System;
using DiemRenLuyen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiemRenLuyen.Migrations
{
    [DbContext(typeof(DiemRenLuyenContext))]
    partial class DiemRenLuyenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.ChiTietPhieu", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaTC")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("DiemSV")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaPhieu", "MaTC");

                    b.HasIndex("MaTC");

                    b.ToTable("ChiTietPhieu");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.DotDanhGia", b =>
                {
                    b.Property<string>("MaDot")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDot");

                    b.ToTable("DotDanhGia", (string)null);

                    b.HasData(
                        new
                        {
                            MaDot = "DG001",
                            HocKy = 1,
                            NamHoc = "2024–2025",
                            ThoiGianBatDau = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ThoiGianKetThuc = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GiangVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaGV = "13103100200",
                            DienThoai = "0901234567",
                            Email = "nguyenvana@example.com",
                            MaKhoa = "CNTT",
                            TenGV = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaGV = "13103100201",
                            DienThoai = "0909876543",
                            Email = "tranthingoc@example.com",
                            MaKhoa = "CNTT",
                            TenGV = "Trần Thị Ngọc"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGVTruongKhoa")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa", (string)null);

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            MaGVTruongKhoa = "10103100001",
                            TenKhoa = "Công nghệ thông tin"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Lop", (string)null);

                    b.HasData(
                        new
                        {
                            MaLop = "DHTI16A1HN",
                            MaGV = "13103100200",
                            MaKhoa = "CNTT",
                            TenLop = "Công nghệ thông tin 1"
                        },
                        new
                        {
                            MaLop = "DHTI16A2HN",
                            MaGV = "13103100200",
                            MaKhoa = "CNTT",
                            TenLop = "Công nghệ thông tin 2"
                        },
                        new
                        {
                            MaLop = "DHTI16A3HN",
                            MaGV = "13103100201",
                            MaKhoa = "CNTT",
                            TenLop = "Công nghệ thông tin 3"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.MinhChung", b =>
                {
                    b.Property<string>("MaMC")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TepDinhKem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaMC");

                    b.HasIndex("MaTC");

                    b.HasIndex("MaPhieu", "MaTC");

                    b.ToTable("MinhChung");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.PhieuDanhGia", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("DaXemKetQua")
                        .HasColumnType("bit");

                    b.Property<string>("MaDot")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongDiem")
                        .HasColumnType("float");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaDot");

                    b.HasIndex("MaSV");

                    b.ToTable("PhieuDanhGia");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien", (string)null);

                    b.HasData(
                        new
                        {
                            MaSV = "22103100228",
                            GioiTinh = true,
                            HoTen = "Trần Văn B",
                            MaLop = "DHTI16A1HN",
                            NgaySinh = new DateTime(2003, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QueQuan = "Ninh Bình"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.TieuChi", b =>
                {
                    b.Property<string>("MaTC")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("MucDiemToiDa")
                        .HasColumnType("float");

                    b.Property<string>("TenTieuChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTC");

                    b.ToTable("TieuChi", (string)null);

                    b.HasData(
                        new
                        {
                            MaTC = "TC01",
                            MoTa = " ",
                            MucDiemToiDa = 10.0,
                            TenTieuChi = "Tham gia học tập tốt"
                        },
                        new
                        {
                            MaTC = "TC02",
                            MoTa = " ",
                            MucDiemToiDa = 15.0,
                            TenTieuChi = "Tích cực tham gia hoạt động lớp"
                        },
                        new
                        {
                            MaTC = "A",
                            MoTa = "Mặc định 70 điểm",
                            MucDiemToiDa = 70.0,
                            TenTieuChi = "Điểm rèn luyện mặc định của sinh viên trong học kỳ"
                        },
                        new
                        {
                            MaTC = "B",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm rèn luyện được cộng trong kỳ (điểm cộng/lần, hoạt động...)"
                        },
                        new
                        {
                            MaTC = "B1",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm cộng về ý thức tham gia học tập"
                        },
                        new
                        {
                            MaTC = "B11",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Đạt kết quả học tập từ 7.0 trở lên (theo thang điểm 10)"
                        },
                        new
                        {
                            MaTC = "B111",
                            MoTa = " ",
                            MucDiemToiDa = 5.0,
                            TenTieuChi = "Đạt điểm trung bình học tập trên 9,0"
                        },
                        new
                        {
                            MaTC = "B112",
                            MoTa = " ",
                            MucDiemToiDa = 3.0,
                            TenTieuChi = "Đạt điểm trung bình học tập từ 8,0 đến 9,0"
                        },
                        new
                        {
                            MaTC = "B113",
                            MoTa = " ",
                            MucDiemToiDa = 2.0,
                            TenTieuChi = "Đạt điểm trung bình học tập từ 7,0 đến 8,0"
                        },
                        new
                        {
                            MaTC = "B12",
                            MoTa = " ",
                            MucDiemToiDa = 2.0,
                            TenTieuChi = "Có tinh thần cố gắng vượt khó, vươn lên trong học tập"
                        },
                        new
                        {
                            MaTC = "B13",
                            MoTa = " ",
                            MucDiemToiDa = 100.0,
                            TenTieuChi = "Tham gia các CLB học thuật, hoạt động NCKH, các cuộc thi khởi nghiệp sáng tạo"
                        },
                        new
                        {
                            MaTC = "B2",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm cộng về ý thức chấp hành nội quy, quy chế, quy định trong nhà trường"
                        },
                        new
                        {
                            MaTC = "B21",
                            MoTa = " ",
                            MucDiemToiDa = 100.0,
                            TenTieuChi = "Có hành động tích cực trên mạng xã hội phù hợp với chủ trương của nhà trường"
                        },
                        new
                        {
                            MaTC = "C",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm rèn luyện bị trừ trong kỳ (điểm trừ/lần vi phạm, buổi...)"
                        },
                        new
                        {
                            MaTC = "C1",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm trừ về ý thức học tập"
                        },
                        new
                        {
                            MaTC = "C11",
                            MucDiemToiDa = 4.0,
                            TenTieuChi = "Vi phạm quy chế thi, kiểm tra"
                        },
                        new
                        {
                            MaTC = "C12",
                            MucDiemToiDa = 2.0,
                            TenTieuChi = "Thi lại môn học, học phần"
                        },
                        new
                        {
                            MaTC = "C13",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Vi phạm thời gian học tập, thiếu ý thức trong học tập"
                        },
                        new
                        {
                            MaTC = "C131",
                            MoTa = " ",
                            MucDiemToiDa = 100.0,
                            TenTieuChi = "Nghỉ học không có lý do"
                        },
                        new
                        {
                            MaTC = "C132",
                            MoTa = " ",
                            MucDiemToiDa = 100.0,
                            TenTieuChi = "Đi học muộn, trốn tiết, bỏ giờ,.."
                        },
                        new
                        {
                            MaTC = "C2",
                            MoTa = " ",
                            MucDiemToiDa = 0.0,
                            TenTieuChi = "Điểm trừ về ý thức chấp hành nội quy, quy chế nhà trường"
                        },
                        new
                        {
                            MaTC = "C21",
                            MoTa = " ",
                            MucDiemToiDa = 100.0,
                            TenTieuChi = "Đi học hộ hoặc nhờ người khác đi học hộ"
                        },
                        new
                        {
                            MaTC = "C22",
                            MoTa = " ",
                            MucDiemToiDa = 5.0,
                            TenTieuChi = "Không đóng học phí đúng thời hạn"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan", (string)null);

                    b.HasData(
                        new
                        {
                            TenDangNhap = "22103100228",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100229",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100230",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100231",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103100232",
                            MatKhau = "123456",
                            VaiTro = "SV"
                        },
                        new
                        {
                            TenDangNhap = "22103110301",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103110302",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103110303",
                            MatKhau = "123456",
                            VaiTro = "GV"
                        },
                        new
                        {
                            TenDangNhap = "22103199901",
                            MatKhau = "admin",
                            VaiTro = "CTSV"
                        },
                        new
                        {
                            TenDangNhap = "22103199902",
                            MatKhau = "admin",
                            VaiTro = "CTSV"
                        });
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.ChiTietPhieu", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.PhieuDanhGia", "PhieuDanhGia")
                        .WithMany("ChiTietPhieus")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.TieuChi", "TieuChi")
                        .WithMany("ChiTietPhieus")
                        .HasForeignKey("MaTC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDanhGia");

                    b.Navigation("TieuChi");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.GiangVien", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.Lop", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.GiangVien", "GiangVien")
                        .WithMany("Lops")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.Khoa", "Khoa")
                        .WithMany("Lops")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.MinhChung", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.PhieuDanhGia", "PhieuDanhGia")
                        .WithMany()
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.TieuChi", "TieuChi")
                        .WithMany()
                        .HasForeignKey("MaTC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.ChiTietPhieu", "ChiTietPhieu")
                        .WithMany("MinhChungs")
                        .HasForeignKey("MaPhieu", "MaTC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietPhieu");

                    b.Navigation("PhieuDanhGia");

                    b.Navigation("TieuChi");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.PhieuDanhGia", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.DotDanhGia", "DotDanhGia")
                        .WithMany("PhieuDanhGias")
                        .HasForeignKey("MaDot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.SinhVien", "SinhVien")
                        .WithMany("PhieuDanhGias")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotDanhGia");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.SinhVien", b =>
                {
                    b.HasOne("DiemRenLuyen.Models.SinhVienModels.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.ChiTietPhieu", b =>
                {
                    b.Navigation("MinhChungs");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.DotDanhGia", b =>
                {
                    b.Navigation("PhieuDanhGias");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.GiangVien", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.Khoa", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.PhieuDanhGia", b =>
                {
                    b.Navigation("ChiTietPhieus");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.SinhVien", b =>
                {
                    b.Navigation("PhieuDanhGias");
                });

            modelBuilder.Entity("DiemRenLuyen.Models.SinhVienModels.TieuChi", b =>
                {
                    b.Navigation("ChiTietPhieus");
                });
#pragma warning restore 612, 618
        }
    }
}
